.\objects\speaker_service.o: ..\..\..\..\components\ble\profiles\ble_audio_profile\speaker_service.c
.\objects\speaker_service.o: D:\Keil_v5\ARM\ARMCC\Bin\..\include\stdio.h
.\objects\speaker_service.o: D:\Keil_v5\ARM\ARMCC\Bin\..\include\string.h
.\objects\speaker_service.o: ..\..\..\..\components\modules\common\include\co_printf.h
.\objects\speaker_service.o: ..\..\..\..\components\ble\include\gap\gap_api.h
.\objects\speaker_service.o: D:\Keil_v5\ARM\ARMCC\Bin\..\include\stdint.h
.\objects\speaker_service.o: D:\Keil_v5\ARM\ARMCC\Bin\..\include\stdbool.h
.\objects\speaker_service.o: ..\..\..\..\components\ble\include\gatt\gatt_api.h
.\objects\speaker_service.o: ..\..\..\..\components\modules\os\include\os_msg_q.h
.\objects\speaker_service.o: ..\..\..\..\components\ble\include\gatt\gatt_sig_uuid.h
.\objects\speaker_service.o: ..\..\..\..\components\ble\profiles\ble_audio_profile\speaker_service.h
.\objects\speaker_service.o: ..\..\..\..\components\driver\include\driver_flash.h
