.\objects\demo_peripheral.o: ..\code\demo_peripheral.c
.\objects\demo_peripheral.o: D:\Keil_v5\ARM\ARMCC\Bin\..\include\stdio.h
.\objects\demo_peripheral.o: D:\Keil_v5\ARM\ARMCC\Bin\..\include\string.h
.\objects\demo_peripheral.o: ..\code\demo_peripheral.h
.\objects\demo_peripheral.o: ..\..\..\..\components\modules\common\include\co_printf.h
.\objects\demo_peripheral.o: ..\..\..\..\components\modules\sys\include\sys_utils.h
.\objects\demo_peripheral.o: D:\Keil_v5\ARM\ARMCC\Bin\..\include\stdint.h
.\objects\demo_peripheral.o: ..\..\..\..\components\modules\platform\include\compiler.h
.\objects\demo_peripheral.o: ..\..\..\..\components\driver\include\driver_ssp.h
.\objects\demo_peripheral.o: ..\..\..\..\components\driver\include\driver_system.h
.\objects\demo_peripheral.o: D:\Keil_v5\ARM\ARMCC\Bin\..\include\stdbool.h
.\objects\demo_peripheral.o: ..\..\..\..\components\driver\include\driver_iomux.h
.\objects\demo_peripheral.o: ..\..\..\..\components\driver\include\driver_plf.h
.\objects\demo_peripheral.o: ..\..\..\..\components\modules\platform\include\core_cm3.h
.\objects\demo_peripheral.o: ..\..\..\..\components\modules\platform\include\cmsis_compiler.h
.\objects\demo_peripheral.o: ..\..\..\..\components\modules\platform\include\cmsis_armcc.h
.\objects\demo_peripheral.o: ..\..\..\..\components\modules\platform\include\ll.h
