.\objects\user_task.o: ..\code\user_task.c
.\objects\user_task.o: D:\Keil_v5\ARM\ARMCC\Bin\..\include\stdint.h
.\objects\user_task.o: ..\..\..\..\components\modules\os\include\os_task.h
.\objects\user_task.o: ..\..\..\..\components\modules\os\include\os_msg_q.h
.\objects\user_task.o: ..\..\..\..\components\modules\os\include\os_mem.h
.\objects\user_task.o: D:\Keil_v5\ARM\ARMCC\Bin\..\include\string.h
.\objects\user_task.o: ..\..\..\..\components\modules\platform\include\compiler.h
.\objects\user_task.o: ..\..\..\..\components\modules\common\include\co_printf.h
.\objects\user_task.o: ..\code\user_task.h
.\objects\user_task.o: ..\..\..\..\components\modules\button\button.h
.\objects\user_task.o: ..\..\..\..\components\driver\include\driver_gpio.h
.\objects\user_task.o: ..\..\..\..\components\driver\include\driver_plf.h
.\objects\user_task.o: ..\..\..\..\components\modules\platform\include\core_cm3.h
.\objects\user_task.o: ..\..\..\..\components\modules\platform\include\cmsis_compiler.h
.\objects\user_task.o: ..\..\..\..\components\modules\platform\include\cmsis_armcc.h
.\objects\user_task.o: ..\..\..\..\components\modules\platform\include\ll.h
.\objects\user_task.o: ..\..\..\..\components\driver\include\driver_system.h
.\objects\user_task.o: D:\Keil_v5\ARM\ARMCC\Bin\..\include\stdbool.h
.\objects\user_task.o: ..\..\..\..\components\driver\include\driver_iomux.h
.\objects\user_task.o: ..\..\..\..\components\modules\peripherals\oled\lcd.h
.\objects\user_task.o: D:\Keil_v5\ARM\ARMCC\Bin\..\include\stdlib.h
.\objects\user_task.o: D:\Keil_v5\ARM\ARMCC\Bin\..\include\stdio.h
.\objects\user_task.o: ..\..\..\..\components\modules\adpcm_ms\adpcm_ms.h
.\objects\user_task.o: ..\..\..\..\components\modules\peripherals\audio\speaker.h
.\objects\user_task.o: ..\..\..\..\components\modules\decoder\decoder.h
.\objects\user_task.o: ..\..\..\..\components\modules\os\include\os_timer.h
.\objects\user_task.o: ..\..\..\..\components\modules\common\include\co_list.h
.\objects\user_task.o: D:\Keil_v5\ARM\ARMCC\Bin\..\include\stddef.h
.\objects\user_task.o: ..\code\ble_simple_peripheral.h
.\objects\user_task.o: ..\..\..\..\components\ble\include\gap\gap_api.h
