.\objects\rtos_entry.o: ..\code\rtos_entry.c
.\objects\rtos_entry.o: ..\..\..\..\components\modules\platform\include\jump_table.h
.\objects\rtos_entry.o: D:\Keil5\ARM\ARMCC\Bin\..\include\stdint.h
.\objects\rtos_entry.o: ..\..\..\..\components\modules\common\include\co_math.h
.\objects\rtos_entry.o: D:\Keil5\ARM\ARMCC\Bin\..\include\stdbool.h
.\objects\rtos_entry.o: D:\Keil5\ARM\ARMCC\Bin\..\include\stdlib.h
.\objects\rtos_entry.o: ..\..\..\..\components\modules\platform\include\compiler.h
.\objects\rtos_entry.o: ..\..\..\..\components\modules\common\include\co_printf.h
.\objects\rtos_entry.o: ..\..\..\..\components\driver\include\driver_plf.h
.\objects\rtos_entry.o: ..\..\..\..\components\modules\platform\include\core_cm3.h
.\objects\rtos_entry.o: ..\..\..\..\components\modules\platform\include\cmsis_compiler.h
.\objects\rtos_entry.o: ..\..\..\..\components\modules\platform\include\cmsis_armcc.h
.\objects\rtos_entry.o: ..\..\..\..\components\modules\platform\include\ll.h
.\objects\rtos_entry.o: ..\..\..\..\components\modules\os\include\os_msg_q.h
.\objects\rtos_entry.o: ..\..\..\..\components\ble\include\gatt\gatt_api.h
.\objects\rtos_entry.o: ..\..\..\..\components\modules\FreeRTOS\include\FreeRTOS.h
.\objects\rtos_entry.o: D:\Keil5\ARM\ARMCC\Bin\..\include\stddef.h
.\objects\rtos_entry.o: ..\..\..\..\components\modules\FreeRTOS\include\FreeRTOSConfig.h
.\objects\rtos_entry.o: ..\..\..\..\components\modules\FreeRTOS\include\projdefs.h
.\objects\rtos_entry.o: ..\..\..\..\components\modules\FreeRTOS\include\portable.h
.\objects\rtos_entry.o: ..\..\..\..\components\modules\FreeRTOS\include\deprecated_definitions.h
.\objects\rtos_entry.o: ..\..\..\..\components\modules\FreeRTOS\portable\keil\portmacro.h
.\objects\rtos_entry.o: ..\..\..\..\components\modules\FreeRTOS\include\mpu_wrappers.h
.\objects\rtos_entry.o: ..\..\..\..\components\modules\FreeRTOS\include\task.h
.\objects\rtos_entry.o: ..\..\..\..\components\modules\FreeRTOS\include\list.h
.\objects\rtos_entry.o: ..\..\..\..\components\modules\FreeRTOS\include\timers.h
.\objects\rtos_entry.o: ..\..\..\..\components\modules\FreeRTOS\include\semphr.h
.\objects\rtos_entry.o: ..\..\..\..\components\modules\FreeRTOS\include\queue.h
.\objects\rtos_entry.o: ..\..\..\..\components\modules\FreeRTOS\include\event_groups.h
