.\objects\lcd.o: ..\..\..\..\components\modules\peripherals\oled\lcd.c
.\objects\lcd.o: ..\..\..\..\components\modules\peripherals\oled\lcd.h
.\objects\lcd.o: D:\Keil_v5\ARM\ARMCC\Bin\..\include\stdlib.h
.\objects\lcd.o: D:\Keil_v5\ARM\ARMCC\Bin\..\include\stdint.h
.\objects\lcd.o: D:\Keil_v5\ARM\ARMCC\Bin\..\include\stdio.h
.\objects\lcd.o: ..\..\..\..\components\modules\peripherals\oled\oledfont.h
.\objects\lcd.o: ..\..\..\..\components\modules\peripherals\oled\bmp.h
.\objects\lcd.o: ..\..\..\..\components\modules\sys\include\sys_utils.h
.\objects\lcd.o: ..\..\..\..\components\modules\common\include\co_printf.h
.\objects\lcd.o: ..\..\..\..\components\modules\platform\include\compiler.h
.\objects\lcd.o: D:\Keil_v5\ARM\ARMCC\Bin\..\include\string.h
.\objects\lcd.o: D:\Keil_v5\ARM\ARMCC\Bin\..\include\stdbool.h
.\objects\lcd.o: ..\..\..\..\components\driver\include\driver_ssp.h
.\objects\lcd.o: ..\..\..\..\components\driver\include\driver_gpio.h
.\objects\lcd.o: ..\..\..\..\components\driver\include\driver_plf.h
.\objects\lcd.o: ..\..\..\..\components\modules\platform\include\core_cm3.h
.\objects\lcd.o: ..\..\..\..\components\modules\platform\include\cmsis_compiler.h
.\objects\lcd.o: ..\..\..\..\components\modules\platform\include\cmsis_armcc.h
.\objects\lcd.o: ..\..\..\..\components\modules\platform\include\ll.h
.\objects\lcd.o: ..\..\..\..\components\driver\include\driver_system.h
.\objects\lcd.o: ..\..\..\..\components\driver\include\driver_iomux.h
.\objects\lcd.o: ..\..\..\..\components\driver\include\driver_pmu.h
.\objects\lcd.o: ..\..\..\..\components\modules\common\include\co_math.h
.\objects\lcd.o: ..\..\..\..\components\driver\include\driver_pmu_regs.h
.\objects\lcd.o: ..\..\..\..\components\driver\include\driver_frspim.h
.\objects\lcd.o: ..\code\ie2.h
