./objects/ota.o: ..\..\..\..\components\ble\profiles\ble_ota\ota.c \
  D:\keil\ARM\ARMCLANG\Bin\..\include\stdint.h \
  D:\keil\ARM\ARMCLANG\Bin\..\include\stdio.h \
  D:\keil\ARM\ARMCLANG\Bin\..\include\string.h \
  ..\..\..\..\components\modules\platform\include\jump_table.h \
  ..\..\..\..\components\modules\common\include\co_math.h \
  D:\keil\ARM\ARMCLANG\Bin\..\include\stdbool.h \
  D:\keil\ARM\ARMCLANG\Bin\..\include\stdlib.h \
  ..\..\..\..\components\modules\platform\include\compiler.h \
  ..\..\..\..\components\modules\os\include\os_mem.h \
  ..\..\..\..\components\driver\include\driver_plf.h \
  ..\..\..\..\components\modules\platform\include\core_cm3.h \
  ..\..\..\..\components\modules\platform\include\cmsis_compiler.h \
  C:\Users\wl123\AppData\Local\Arm\Packs\ARM\CMSIS\5.9.0\CMSIS\Core\Include\cmsis_armclang.h \
  ..\..\..\..\components\modules\platform\include\ll.h \
  ..\..\..\..\components\driver\include\driver_system.h \
  ..\..\..\..\components\driver\include\driver_iomux.h \
  ..\..\..\..\components\driver\include\driver_flash.h \
  ..\..\..\..\components\driver\include\driver_wdt.h \
  ..\..\..\..\components\driver\include\driver_pmu.h \
  ..\..\..\..\components\driver\include\driver_pmu_regs.h \
  ..\..\..\..\components\driver\include\driver_frspim.h \
  ..\..\..\..\components\driver\include\driver_uart.h \
  ..\..\..\..\components\ble\include\gatt\gatt_api.h \
  ..\..\..\..\components\modules\os\include\os_msg_q.h \
  ..\..\..\..\components\ble\include\gap\gap_api.h \
  ..\..\..\..\components\modules\sys\include\sys_utils.h \
  ..\..\..\..\components\modules\common\include\co_printf.h \
  ..\..\..\..\components\ble\profiles\ble_ota\ota.h \
  ..\..\..\..\components\ble\profiles\ble_ota\ota_service.h \
  ..\code\flash_usage_config.h \
  ..\..\..\..\components\modules\os\include\os_timer.h
