.\objects\gyro_driver.o: ..\..\..\..\components\modules\peripherals\gyro\gyro_driver.c
.\objects\gyro_driver.o: D:\Keil_v5\ARM\ARMCC\Bin\..\include\stdio.h
.\objects\gyro_driver.o: D:\Keil_v5\ARM\ARMCC\Bin\..\include\stdint.h
.\objects\gyro_driver.o: ..\..\..\..\components\modules\os\include\os_timer.h
.\objects\gyro_driver.o: D:\Keil_v5\ARM\ARMCC\Bin\..\include\stdbool.h
.\objects\gyro_driver.o: ..\..\..\..\components\driver\include\driver_iic.h
.\objects\gyro_driver.o: ..\..\..\..\components\driver\include\driver_iomux.h
.\objects\gyro_driver.o: ..\..\..\..\components\modules\peripherals\gyro\gyro_alg.h
.\objects\gyro_driver.o: ..\..\..\..\components\driver\include\driver_system.h
.\objects\gyro_driver.o: ..\..\..\..\components\modules\sys\include\sys_utils.h
.\objects\gyro_driver.o: ..\..\..\..\components\modules\common\include\co_printf.h
.\objects\gyro_driver.o: ..\..\..\..\components\modules\platform\include\compiler.h
