.\objects\simple_gatt_service.o: ..\..\..\..\components\ble\profiles\ble_simple_profile\simple_gatt_service.c
.\objects\simple_gatt_service.o: D:\Keil5\ARM\ARMCC\Bin\..\include\stdio.h
.\objects\simple_gatt_service.o: D:\Keil5\ARM\ARMCC\Bin\..\include\string.h
.\objects\simple_gatt_service.o: ..\..\..\..\components\modules\common\include\co_printf.h
.\objects\simple_gatt_service.o: ..\..\..\..\components\ble\include\gap\gap_api.h
.\objects\simple_gatt_service.o: D:\Keil5\ARM\ARMCC\Bin\..\include\stdint.h
.\objects\simple_gatt_service.o: D:\Keil5\ARM\ARMCC\Bin\..\include\stdbool.h
.\objects\simple_gatt_service.o: ..\..\..\..\components\ble\include\gatt\gatt_api.h
.\objects\simple_gatt_service.o: ..\..\..\..\components\modules\os\include\os_msg_q.h
.\objects\simple_gatt_service.o: ..\..\..\..\components\ble\include\gatt\gatt_sig_uuid.h
.\objects\simple_gatt_service.o: ..\..\..\..\components\driver\include\driver_flash.h
.\objects\simple_gatt_service.o: ..\code\user_task.h
.\objects\simple_gatt_service.o: ..\..\..\..\components\ble\profiles\ble_simple_profile\simple_gatt_service.h
