.\objects\my_user.o: ..\code\my_user.c
.\objects\my_user.o: D:\Keil5\ARM\ARMCC\Bin\..\include\stdint.h
.\objects\my_user.o: D:\Keil5\ARM\ARMCC\Bin\..\include\stdbool.h
.\objects\my_user.o: ..\..\..\..\components\modules\os\include\os_timer.h
.\objects\my_user.o: ..\..\..\..\components\ble\include\gap\gap_api.h
.\objects\my_user.o: D:\Keil5\ARM\ARMCC\Bin\..\include\stdio.h
.\objects\my_user.o: ..\..\..\..\components\ble\include\gatt\gatt_api.h
.\objects\my_user.o: ..\..\..\..\components\modules\os\include\os_msg_q.h
.\objects\my_user.o: ..\..\..\..\components\driver\include\driver_gpio.h
.\objects\my_user.o: ..\..\..\..\components\driver\include\driver_plf.h
.\objects\my_user.o: ..\..\..\..\components\modules\platform\include\compiler.h
.\objects\my_user.o: ..\..\..\..\components\modules\platform\include\core_cm3.h
.\objects\my_user.o: ..\..\..\..\components\modules\platform\include\cmsis_compiler.h
.\objects\my_user.o: ..\..\..\..\components\modules\platform\include\cmsis_armcc.h
.\objects\my_user.o: ..\..\..\..\components\modules\platform\include\ll.h
.\objects\my_user.o: ..\..\..\..\components\driver\include\driver_system.h
.\objects\my_user.o: ..\..\..\..\components\driver\include\driver_iomux.h
.\objects\my_user.o: ..\..\..\..\components\ble\profiles\ble_simple_profile\simple_gatt_service.h
.\objects\my_user.o: D:\Keil5\ARM\ARMCC\Bin\..\include\string.h
.\objects\my_user.o: ..\..\..\..\components\ble\include\gatt\gatt_sig_uuid.h
.\objects\my_user.o: ..\code\ble_simple_peripheral.h
.\objects\my_user.o: D:\Keil5\ARM\ARMCC\Bin\..\include\inttypes.h
.\objects\my_user.o: ..\..\..\..\components\modules\sys\include\sys_utils.h
.\objects\my_user.o: ..\..\..\..\components\modules\common\include\co_printf.h
.\objects\my_user.o: ..\code\flash_usage_config.h
.\objects\my_user.o: ..\code\user_task.h
.\objects\my_user.o: ..\..\..\..\components\driver\include\driver_flash.h
.\objects\my_user.o: ..\..\..\..\components\driver\include\driver_uart.h
.\objects\my_user.o: ..\..\..\..\components\modules\os\include\os_mem.h
